### ISSUE TITLE
Why is embed_grad scaled up by batch_size?

### ISSUE THREAD

**Issue by eric-haibin-lin** [rafaljozefowicz/lm#5]
https://github.com/rafaljozefowicz/lm/blob/master/language_model.py#L119-L122

```
        for i in range(len(emb_grads)):
            assert isinstance(emb_grads[i], tf.IndexedSlices)
            emb_grads[i] = tf.IndexedSlices(emb_grads[i].values * hps.batch_size, emb_grads[i].indices,
                                            emb_grads[i].dense_shape)

```

why is emb_grad modified this way?

**Comment by ciprian-chelba** [comment]
Would you please share the answer?

**Comment by eric-haibin-lin** [comment]
@ciprian-chelba 
I asked the author, he said it usually works better empirically and shouldn't make a huge difference if you don't scale it.
